default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  user: postgres

development:
  <<: *default
  database: ng-forms-api_development

test:
  <<: *default
  database: ng-forms-api_test

production:
  <<: *default
  database: ng-forms-api_production
  username: ng-forms-api
  password: <%= ENV['NG-FORMS-API_DATABASE_PASSWORD'] %>
